Elice-8Team/MealAi-Client

src/components/molecules/SelectWithLabel.tsx, src/pages/Home.tsx
=> feat(✨) - components - select

src/components/atoms/BasicButton.tsx, src/components/atoms/TinyButton.tsx, src/pages/Home.tsx, src/utils/GetStyle.ts, tailwind.config.js
- 공통 컴포넌트 작성
BasicButton, TinyButton
- 버튼 컴포넌트 내에서 사용되는 스타일 함수 작성
utils > GetStyle
- tailwind.config.js 내용 수정
daisyui - utils : false > true
```
daisyui: {
styled: true,
base: true,
utils: true,
logs: true,
rtl: false,
},
```
=>  feat(✨) - 버튼 컴포넌트 작성 및 config 수정

src/styles/global-styles.tsx, tailwind.config.js
- 글로벌 폰트 스타일을 적용 했습니다
- bg 2 컬러테마를 추가했습니다
```
import { createGlobalStyle } from "styled-components";
import reset from "styled-reset";
export const GlobalStyle = createGlobalStyle`
${reset}
@import url("https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard-dynamic-subset.css");
*,
*::after,
*::before {
box-sizing: border-box;
-moz-osx-font-smoothing: grayscale;
-webkit-font-smoothing: antialiased;
font-smoothing: antialiased;
font-family: pretendard, sans-serif !important;
}
`;
```
```
theme: {
extend: {
colors: {
"gray-1": "#272520",
"gray-2": "#3C3932",
"gray-3": "#53514C",
"gray-4": "#6B6A67",
"gray-5": "#878681",
"gray-6": "#A6A4A0",
"gray-7": "#D3D3D3",
"gray-8": "#EAE9E9",
"gray-9": "#F5F5F5",
"primary-1": "#008B47",
"primary-2": "#6BB64A", …
```
=> chore : fontset on global-style, added color theme

src/components/errorrBoundary/CustomError.tsx
Error Boundary 컴포넌트
클래스형에서 함수형으로 전환 함.
=> [♻️Refactor]  함수형 컴포넌트로 전환

src/App.tsx, src/components/templates/Footer.tsx, src/components/templates/Header.tsx, src/components/templates/Layout.tsx, src/pages/Home.tsx, src/router/AppRouter.tsx
페이지마다 공통 적용되는 Layout을 작업하고 라우터에 적용했습니다.
라우터는 코치님의 도움을 받아 일부 리팩토링 했습니다.
- 페이지마다 공통 적용되는 Layout 작업
- router > CustomRouter 리팩토링
- 이름 수정 : CustomRouter > AppRouter
- Layout 적용
- 변수명 수정
=> refactor(♻️) - layout 적용, custom router 수정

.eslintrc.json, src/App.tsx, src/components/atoms/buttons/LikeButton.tsx, src/components/atoms/inputs/SearchInput.tsx, src/components/organisms/LikeWithCount.tsx, src/components/templates/Footer.tsx, src/components/templates/Layout.tsx, src/pages/Home.tsx
- footer, 검색 input, like button variation component를 추가했습니다.
- eslint의 import error 설정을 off 했습니다.
=> feat(✨) - components 작업, eslint 설정 변경 (no-unused-vars)

src/components/atoms/badge/Badge.tsx, src/components/atoms/goal/GoalText.tsx, src/components/atoms/inputs/ValidationInput.tsx, src/components/organisms/LikeWithCount.tsx, src/components/templates/Layout.tsx, src/pages/Home.tsx
- badge와 vaildation input 컬러 렌더링이 되지 않는 버그를 해결했습니다
- 목표 텍스트 components 제작
=> fix(🐛) - color style rendering bug fix

src/components/atoms/buttons/RadioButton.tsx, src/pages/Home.tsx
RadioButton 컴포넌트 구현
입력 값에 따라 라벨에 성별 구분되도록 구현함.
```
<label htmlFor="radio-button">{gender === "M" ? "남자" : "여자"}</label>
```
```
<RadioButton type="radio" id="gender-m" name="gender" gender="M" onChange={() => {}} />
<RadioButton type="radio" id="gender-f" name="gender" gender="F" onChange={() => {}} />
```
=>     feat(✨) - RadioButton 구현

src/components/atoms/buttons/ToggleButton.tsx, src/pages/Home.tsx
=> feat(✨) - ToggleButton 구현

.eslintrc.json, src/components/atoms/progressBars/HorizontalProgressBars.tsx, src/components/atoms/progressBars/VerticalProgressBars.tsx, src/pages/Home.tsx, src/utils/getProgressBarColor.tsx, src/utils/getProgressBarPercent.tsx, tailwind.config.js
영양소 그래프 바 가로형, 세로형 컴포넌트 작업
eslint의 no-shadow 설정이 타스는 안꺼져 있어서,, 자꾸 오류를 뱉길래 껐습니다.
```
"no-shadow": "off",
"@typescript-eslint/no-shadow": "off",
```
=> feat(✨) - components ; 영양소 그래프 바 컴포넌트 작업

src/components/atoms/loader/Loader.tsx, src/components/templates/Layout.tsx, src/router/AppRouter.tsx, tailwind.config.js
=> feat(✨) - loading 구현

src/pages/auth/Goal.tsx, src/router/AppRouter.tsx
=> feat(✨) - 목표설정 페이지 CSS 구현

src/components/atoms/inputs/ValidationInput.tsx, src/components/templates/Header.tsx, src/pages/auth/FindPassword.tsx, src/pages/auth/Goal.tsx, src/pages/auth/SignIn.tsx, src/pages/auth/SignUp.tsx, src/router/AppRouter.tsx, tailwind.config.js
- 회원가입/로그인 관련 auth 페이지 CSS 및 간단한 버튼 조작 구현 완료
- 소셜 회원 추가정보 페이지 미구현
=> feat(✨) - 회원가입/로그인 관련 페이지 CSS 구현 완료

src/pages/feeds/Feeds.tsx, tailwind.config.js
- 식단톡 메인 페이지 CSS 구현
- 썸네일, 카테고리 부분 API 명세 확인 후 추후 보완 필요함
=> feat(✨) - 식단톡 메인 페이지 CSS 구현

src/components/atoms/buttons/RadioButton.tsx, src/components/atoms/cards/ReportInfoCards.tsx, src/components/organisms/Modal.tsx, src/components/templates/Header.tsx, src/pages/Home.tsx, src/pages/mylog/WeeklyReport.tsx, src/router/AppRouter.tsx, tailwind.config.js
=> feat(✨) - 식단일지 주간 리포트 페이지 CSS 구현

src/pages/feeds/Feeds.tsx
- 식단톡 피드 페이지(Feeds) 최신순 카테고리 렌더링시 바로 활성화
- clickNewest state를 true로 설정
=> refactor(♻️) - 식단톡 피드 페이지 최신순 카테고리 활성화

src/pages/auth/FindPassword.tsx
- 비밀번호 찾기 페이지에서 이메일 입력시 검증 필요
- 이메일 입력 input을 validation input으로 변경
=> refactor(♻️) - 비밀번호 찾기 페이지 validation input으로 변경

src/components/atoms/inputs/SearchInput.tsx, src/components/organisms/SearchResult.tsx, src/pages/Test.tsx, src/pages/meal-ai/Result.tsx
=> feat(✨) - ai 분석결과 페이지 modal 정리

src/api/auth/index.ts, src/pages/auth/Goal.tsx, src/pages/auth/SignUp.tsx, src/types/auth/authTypes.ts, src/utils/validation.ts
- 회원가입 페이지 이메일 인증, 비밀번호, 비밀번호 확인 검증 구현
=> fix(🐛) - 회원가입 validation 구현

.eslintrc.json, src/api/auth/index.ts, src/api/user/index.ts, src/components/atoms/buttons/AddImageFileInput.tsx, src/components/organisms/GoalText.tsx, src/components/organisms/InputWithLabel.tsx, src/components/organisms/SearchResult.tsx, src/components/templates/Header.tsx, src/pages/Home.tsx, src/pages/auth/SignIn.tsx, src/pages/auth/SignUp.tsx, src/pages/meal-ai/Ai.tsx, src/pages/mypage/MyPage.tsx, src/types/auth/authTypes.ts, src/types/user/userTypes.ts, src/utils/axios.utils.ts
- 마이페이지에서 사용되는 모달 기능 작업했습니다
- 리프레시 토큰 구현했으나 아직 좀 더 보완이 필요합니다 (백엔드와 협의)
=> feat(✨) - 마이페이지 - 비번 확인, 비번찾기 모달 기능 구현, refresh token

src/api/auth/index.ts, src/pages/auth/FindPassword.tsx, src/pages/auth/SignIn.tsx, src/pages/auth/SignUp.tsx, src/pages/mypage/MyPage.tsx
비회원일 때 이용하는 로그인, 회원가입, 비밀번호 찾기 페이지에
토큰이 있을 때 접근하지 못하도록 설정했습니다
=> fix(🐛) -  비회원 전용 페이지 bug fix

src/components/organisms/GoalButtons.tsx, src/components/organisms/GoalText.tsx, src/components/organisms/SelectWithLabel.tsx, src/pages/auth/Goal.tsx, src/pages/mypage/EditInfo.tsx, src/pages/mypage/MyPage.tsx
=> hotfix(🚑️) - goal type 수정

src/api/auth/index.ts, src/pages/auth/Goal.tsx, src/pages/auth/SignUp.tsx
- 회원가입, 목표설정 페이지에서 모든 정보가 올바르게 입력되어야 버튼이 활성화 되도록 구현.
- 버튼 deactivated를 제어하는 함수 작성
=> feat(✨)/issue number#71 - 회원가입 및 목표 설정 올바르게 입력되어야 버튼 활성화 되도록 구현

src/hooks/useIntersectionObserver.ts, src/pages/feeds/Feeds.tsx, src/pages/mypage/MyPage.tsx
- 최신순 / 인기순 별 피드 조회
- 사용자가 설정한 목표(균형잡힌 식단 / 다이어트 / 근력보강 / 키토제닉)별 피드 조회
- api로 받아오는 데이터로 정확한 내용 확인되지 않아 console.log로 필터 변화 부분 출력함.
- 추후 올바른 데이터 인입시 확인 필요함.
- Infinite Scroll 구현중으로 변경 가능성 높음.
=> feat(✨) - 필터로 피드 불러오기 구현

src/api/feeds/index.ts, src/components/atoms/thumbnail/Thumbnail.tsx, src/components/organisms/GoalText.tsx, src/components/templates/Header.tsx, src/pages/auth/SignIn.tsx, src/pages/feeds/Detail.tsx, src/pages/feeds/Feeds.tsx, src/pages/mypage/MyPage.tsx, src/types/feeds/feedsResponseTypes.ts, src/utils/getMealTime.tsx
피드 상세 페이지의 좋아요 기능 구현 했습니다.
다른 기능은 작업 중입니다.
=> feat(✨) - 피드 상세 구현중 (좋아요 구현 완료)

src/pages/Home.tsx, src/pages/feeds/Feeds.tsx, src/types/feeds/feedsRequestTypes.ts, src/types/feeds/feedsResponseTypes.ts
- 식단톡 페이지 진입시 인기랭킹 피드 노출
- 식단 피드와 구분하기 위하여 인기 랭킹 피드 조회하는 api 호출 분리.
- 최초 진입시에만 호출하여 보여지도록 함.
=> feat(✨) - 식단톡 페이지 인기랭킹 피드 조회 구현

src/api/feeds/index.ts, src/pages/Home.tsx, src/pages/feeds/Detail.tsx, src/pages/feeds/Feeds.tsx, src/pages/mypage/MyPage.tsx, src/types/feeds/feedsRequestTypes.ts, src/types/feeds/feedsResponseTypes.ts
=> refactor(♻️) - feeds types 수정

src/components/atoms/progressBars/HorizontalProgressBars.tsx, src/pages/feeds/Feeds.tsx, src/pages/mylog/MyLog.tsx, src/pages/mylog/WeeklyReport.tsx, src/types/report /reportResponseType.ts
=> feat(✨) : report nutry api 연결

package.json, src/api/feeds/index.ts, src/components/atoms/buttons/AddImageFileInput.tsx, src/components/templates/Header.tsx, src/pages/feeds/Feeds.tsx, src/pages/meal-ai/Ai.tsx, src/pages/mypage/MyPage.tsx, src/types/feeds/feedsRequestTypes.ts, yarn.lock
AI분석 페이지 post feed 구현
- 합치신후 yarn install 하셔서 패키지 새로 설치 바랍니다 (useForm 추가)
=> feat(✨) - AI분석 페이지 post feed 구현

src/api/feeds/index.ts, src/pages/feeds/Detail.tsx, src/pages/feeds/Edit.tsx, src/pages/feeds/Feeds.tsx, src/types/feeds/feedsRequestTypes.ts
=> feat(✨) - 피드 식단 수정 작업중

src/components/atoms/thumbnail/Thumbnail.tsx, src/components/templates/Header.tsx, src/pages/auth/SignIn.tsx, src/pages/feeds/Detail.tsx, src/pages/mypage/EditInfo.tsx, src/utils/axios.utils.ts
**fix**
- 상세화면 foodCards css 수정
- 회원탈퇴후 header reset (수정 작업 중)
**feat**
- 썸네일 src url
- interceptor 수정 (추가 작업 필요 - 관련 내용 [Link](https://www.notion.so/elice/Custom-Error-61fa30cd356c42df87c04dcbd256e50c?pvs=4#73ba2d840bad4de9b4ef03313f02a232) )
=> feat(✨) - axios multiple requests 관련 interceptor 수정 & 각종 bug fix

src/pages/mylog/WeeklyReport.tsx
=> feat(✨) - 주간 리포트 기능 구현 완료

src/api/feeds/index.ts, src/components/templates/Header.tsx, src/utils/axios.utils.ts
토큰 관련 error code가 response 올 경우
2001번을 제외한 모든 오류는 브라우저상의 토큰을 모두 지우고 로그인을 유도하도록 수정했습니다.
앞으로 토큰은 2001(EXPIRED_ACCESS_TOKEN) error일 경우에만 재발급 됩니다.
=> fix(🐛) -  axios interceptor error code 수정

src/pages/mypage/MyPage.tsx, src/utils/axios.utils.ts
=> fix(🐛) - axios 2001 에러 해결

src/api/feeds/index.ts, src/components/organisms/SearchResult.tsx, src/pages/Test.tsx, src/pages/feeds/Edit.tsx, src/pages/feeds/Feeds.tsx, src/pages/meal-ai/Result.tsx, src/types/feeds/feedsRequestTypes.ts, src/types/feeds/feedsResponseTypes.ts, src/utils/axios.utils.ts
- 식단톡 피드 수정 페이지 작업
- 식단 수정 검색 모달 api 조회 구현
=> feat(✨) - 음식명 키워드 조회 구현

src/components/atoms/inputs/SearchInput.tsx, src/components/organisms/FoodCard.tsx, src/components/organisms/SearchResult.tsx, src/pages/feeds/Detail.tsx, src/pages/meal-ai/Result.tsx, src/types/feeds/feedsRequestTypes.ts
=> feat(✨) - 분석결과 수정/삭제 반영

src/pages/feeds/Edit.tsx
- 식단톡 피드 수정 화면 접근시 작성자의 피드 공개여부 반영
- 작성자의 기존 데이터 불러올 때 공개여부 반영되도록 설정
```typescript
useEffect(() => {
const getFeed = async () => {
const data = await feedsApi.getFeedRequest(`/api/feeds/${id}`);
if (data.status === 200) {
setFeedDetail(data.data);
setFoodCards(data.data.foods);
setIsMine(data.data.is_mine);
setIsOpen(data.data.open);
setNutry({
kcal: data.data.kcal,
carbohydrate: data.data.carbohydrate,
protein: data.data.protein,
fat: data.data.fat,
}); // 피드영양정보
} else {
alert(data.response.data.message);
navigate(-1);
}
};
getFeed();
}, []);
```
=> feat(✨) -식단톡 수정시 공개여부 반영

src/components/organisms/FoodCard.tsx, src/pages/meal-ai/Ai.tsx, src/pages/meal-ai/Result.tsx
분석결과, 피드수정 화면에서 foodCards 삭제 후
다음 배열 카드의 정보가 삭제된 카드의 정보로 출력되던 bug를 수정했습니다.
=> fix(🐛) - foodCards bug fix

src/components/atoms/thumbnail/Thumbnail.tsx, src/pages/feeds/Detail.tsx, src/pages/feeds/Edit.tsx, src/pages/feeds/Feeds.tsx, src/pages/meal-ai/Result.tsx, src/pages/mylog/MyLog.tsx, src/utils/getMealTime.tsx
- 로그인 상태에서 식단 분석 후 식단일지 페이지로 연결되도록 수정.
=> refactor(♻️) - 분석 완료 후 식단일지 페이지 링크 연결

src/pages/feeds/Feeds.tsx
=>  test(✅) - 배포 Test

src/components/atoms/aiRule/AiRule.tsx, src/components/templates/Layout.tsx, src/pages/Home.style.ts, src/pages/Home.tsx, src/pages/meal-ai/Ai.tsx
- 브라우저 가로 너비를 좁게 줄였을 때 y스크롤이 충분히 생기지 않던 문제를 수정햇습니다
- ai 분석 중 비활성화된 버튼 내 텍스트를 [로딩중...]으로 조작
=> fix(🐛) - layout min-width fix (y 스크롤 짤림 현상 해결) & ai분석 ux 수정

src/components/atoms/thumbnail/Thumbnail.tsx, src/pages/mylog/MyLog.tsx, src/utils/getMealTime.tsx
=> feat : 식댠일지 수정 사항 반영

src/components/atoms/inputs/Input.tsx, src/components/organisms/SelectWithLabel.tsx, src/pages/auth/SignUp.tsx, src/pages/feeds/Detail.tsx, src/pages/feeds/Edit.tsx, src/pages/feeds/Feeds.tsx, src/recoil/state.ts
- QA 이슈 해결
- 회원가입 이메일 인증시 인증코드 입력 input 제어 설정
- 식단톡 목표별 카테고리 조회에서 해당 피드가 없을 경우 안내 메세지 추가
- 피드 삭제 후 이전페이지로 이동
- 피드 수정 여부에 따른 목록 버튼 페이지이동 분기
=> refactor(♻️) - QA 이슈 해결

src/pages/mylog/MyLog.tsx, src/pages/mylog/WeeklyReport.tsx, tailwind.config.js, yarn.lock
- 식단일지, 리포트 페이지 일부 코드를 수정하고 빈 데이터일 경우 화면단 방어코드를 추가했습니다
- tailwindcss 운영체제 설정에 따라 다크모드가 적용되는 현상을 fix하기 위한 설정을 바꿨습니다 (test)
다크모드 -> @cielplace 시엘님 확인 필요
=> fix(🐛) - 코드 수정, 방어로직 추가 & tailwindcss 다크모드 삭제 test

package-lock.json, package.json, src/pages/mylog/MyLog.tsx, yarn.lock
=> feat : unique key error uuid로 해결

src/api/auth/index.ts, src/components/templates/Header.tsx, src/pages/auth/SignIn.tsx, src/utils/axios.utils.ts
=> test(✅) - token cookie test

src/components/templates/Header.tsx, src/utils/axios.utils.ts
=> test : token console

src/api/auth/index.ts
=> test : refresh api method 수정

src/utils/axios.utils.ts
=> test : axios token setting 수정

src/utils/axios.utils.ts
axios interceptor의 refresh token 함수bug fix & console.log 삭제
=> feat(✨) - refresh token bug fix

src/components/templates/Layout.tsx
1200px 이하 화면에서 footer의 오른쪽 부분이 비어보이게 나오던 것을 고쳤습니다
=> fix(🐛) - 화면 줄였을 때 footer 잘리는 현상 해결 (css fix)
